# Software modules and tool configurations
plink2:
  module: "plink2/2.00a3.3lm"
  version: "2.00a3.3lm"
  params:
    memory: "--memory 32000"
    threads: "--threads 2"

plink1:
  module: "plink2/1.90b3w"
  version: "1.90b3w"
  params:
    memory: "--memory 32000"
    threads: "--threads 2"

r:
  module: "R/4.4.1-mkl"
  version: "4.4.1"
  params:
    susieR_max_causal: "10"
    coverage: "0.95"

finemap:
  module: "finemap/1.4"
  version: "1.4"
  params:
    threads: "4"
    max_causal_snps: "2"
    credible_threshold: "0.95"
    maf_threshold: "0.1"

python:
  module: "python"
numpy:
  module: "numpy"
  version: "1.21.0"

bcftools:
  module: "bcftools/1.15"
  version: "1.15"
  params:
    output_type: "-O z"
    threads: "--threads 2"
R:
  module: "R/4.4.1-mkl"
  version: "4.4.1"


annovar:
  module: "annovar/2018Apr16"
  version: "2018Apr16"
  params:
    memory: "--memory 32000"
    threads: "--threads 2"
    annovar_db_dir: "/s/nath-lab/alsamman/__Data__/HarmonizingRef/annovar_db"